Log error when invalid contract paths are selected by user
specmatic/specmatic pull request #1140
Opened 2024-06-09 08:23 UTC by yogeshnikam671

**What**:
If we run the test against a folder (i.e. not a valid contract file path),
we get following log messages -
```
Endpoints API not found, cannot calculate actual coverage

Could not load report configuration, coverage will be calculated but no coverage threshold will be enforced
The Open API coverage report generated is blank.
This can happen if you have included all the endpoints in the 'excludedEndpoints' array in the report section in specmatic.json, or if your open api specification does not have any paths documented.
```

It does not mention that it is failing because a file with valid extension was not selected.

With this change, we will get additional error message as follows -
```
Could not load report configuration, coverage will be calculated but no coverage threshold will be enforced
The Open API coverage report generated is blank.
This can happen if you have included all the endpoints in the 'excludedEndpoints' array in the report section in specmatic.json, or if your open api specification does not have any paths documented.

No valid specification file found at given paths : /Users/yogeshanandanikam/personal_projects/specmatic-intellij-plugin
```

**Why**:
Better user experience.

**How**:
Logs a message when the contract paths are not empty but none of them is valid.

**Checklist**:

- [ ] Documentation added to the README.md OR link to PR on https://github.com/specmatic/specmatic-documentation
- [x] Tests
- [ ] Sonar Quality Gate

**Issue ID**:
Closes: #123

2024-06-13 07:26 UTC, harikrishnan83 requested changes
Should we do this for stub?

2024-07-10 05:24 UTC, joelrosario reviewed
Hi @yogeshnikam671, thanks, the logic looks good. I've requested a few changes with respect to removing duplication and the format of the error message.

2024-07-10 05:24 UTC, joelrosario commented on core/src/main/kotlin/in/specmatic/stub/api.kt
> +    val validContractPaths = contractPaths.filter { path ->
The logic for filtering is duplicated 3 times. Can you pull it out into a common function?

2024-07-10 05:24 UTC, joelrosario commented on core/src/main/kotlin/in/specmatic/stub/api.kt
> +        throw ContractException("No valid specification file found at given paths : $contractPaths")
contractPaths here is a list. Can you confirm that it appears as a CSV when the error message is printed?

The same applies to the change to createStubFromContracts on line 96 in this file.

2024-07-11 04:22 UTC, joelrosario approved these changes
LGTM

2024-07-11 04:23 UTC, merged