Alias `test` to `exposes` and `stub` to `depends` for Specmatic Config.
specmatic/specmatic pull request #1185
Opened 2024-07-17 09:07 UTC by StarKhan6368

**What**: Alias `test` to `exposes` and `stub` to `depends`

**Why**: 

**How**:  Using the `@JsonAlias` annotation.

**Checklist**:

- [ ] Documentation added to the README.md OR link to PR on https://github.com/specmatic/specmatic-documentation
- [x] Tests
- [ ] Sonar Quality Gate

2024-07-17 09:38 UTC, joelrosario requested changes
@StarKhan6368 can you test these in the sample projects as well by updating specmatic.yml / json to use dependencies and exposes (both specmatic-order-bff-java and specmatic-order-api-java)

2024-07-17 09:38 UTC, joelrosario commented on core/src/main/kotlin/in/specmatic/core/SpecmaticConfig.kt
> +    @field:JsonAlias("depends")
This should be `dependencies`

2024-07-18 07:10 UTC, joelrosario commented on core/src/test/resources/specmaticConfigFiles/specmatic_exp_dep.json
> +        "com/petstore/1.spec"
Can you use yaml instead of spec for the extensions, as .spec is the legacy format.

2024-07-18 07:26 UTC, joelrosario requested changes
I've added a comment requesting changes.

2024-07-18 07:35 UTC, StarKhan6368 commented on core/src/test/resources/specmaticConfigFiles/specmatic_exp_dep.json
> +        "com/petstore/1.spec"
Renamed OAS file extensions to .yaml instead of legacy .spec, updated the test expectations as well.

2024-07-18 13:37 UTC, joelrosario approved these changes
LGTM

2024-07-18 13:38 UTC, merged