Stop auto-generation of mandatory query params and headers missing in example
specmatic/specmatic pull request #1353
Opened 2024-10-11 10:08 UTC by yogeshnikam671

**What**:
Disable auto-generation of mandatory query param/header which is intentionally not specified in an example to emulate a negative scenario

**Why**:
If a user wants to specify an example where a mandatory query param is missing, currently specmatic auto-generates that mandatory query param even though it is not present in the example.
To fix this behaviour, this PR has been raised.

**Checklist**:

- [ ] Documentation added to the README.md OR link to PR on https://github.com/specmatic/specmatic-documentation
- [x] Tests
- [ ] Sonar Quality Gate

2024-10-11 14:11 UTC, joelrosario requested changes
While Specmatic allows examples where mandatory query params or headers are missing for 400 status responses, there is no reason to permit an example (one that has omitted mandatory query params or headers) when it is not an example of a bad request.

This logic should therefore not apply to non 4xx statuses. It should only apply specifically to 4xx statuses.

2024-10-11 14:41 UTC, joelrosario approved these changes

2024-10-14 06:50 UTC, yogeshnikam671 commented
Hey @joelrosario, I've addressed the point raised by you. Please let me know your feedback on the same if any. Thanks.

2024-10-14 13:03 UTC, joelrosario approved these changes

2024-10-14 13:03 UTC, merged