Feature/UUID pattern
specmatic/specmatic pull request #652
Opened 2023-05-16 12:12 UTC by androa

**What**: Add support for UUIDs
**Why**: UUIDs are quite essentials in APIs
**How**: By generating UUIDs in the same way as DateTime
**Checklist**:
- [ ] Documentation added to the README.md OR link to PR on https://github.com/specmatic/specmatic-documentation
- [x] Tests
- [x] Sonar Quality Gate

2023-06-04 10:39 UTC, harikrishnan83 requested changes
hello @androa, thanks a lot for this PR. @joelrosario and I have taken a look at it and overall looks good to merge. A few small points that may need to be addressed to take this completion.
- DatePattern has to be wired to OpenAPISpecification [here](https://github.com/znsio/specmatic/blob/f3a3b0eef2f2e44e54359fb42a1634847675eac1/core/src/main/kotlin/in/specmatic/conversions/OpenApiSpecification.kt#L581)
- UUIDPattern has to be wired to OpenAPISpecification [here](https://github.com/znsio/specmatic/blob/f3a3b0eef2f2e44e54359fb42a1634847675eac1/core/src/main/kotlin/in/specmatic/conversions/OpenApiSpecification.kt#L580)
- And some minor renaming related comments that we have added to this PR.

We are assuming we can merge this PR and it will take care of adding both DatePattern and UUIDPattern and we can abandon your [other PR](https://github.com/znsio/specmatic/pull/651) which only adds DatePattern.

Again, appreciate the contribution very much and we will merge this as soon as above comments are addressed.

2023-06-04 10:39 UTC, harikrishnan83 commented on core/src/test/kotlin/in/specmatic/core/pattern/UUIDPatternTest.kt
> +        val datePatterns = UUIDPattern.newBasedOn(Row(), Resolver())
should this be called uuidPatterns?

2023-06-04 10:39 UTC, harikrishnan83 commented on core/src/test/kotlin/in/specmatic/core/pattern/UUIDPatternTest.kt
> +        val date1 = StringValue("cfb64879-6e10-47f6-a824-a7606a36d423")
similar to above comment, should we call these uuid1 and uuid2?

2023-06-04 10:39 UTC, harikrishnan83 commented on core/src/test/kotlin/in/specmatic/core/pattern/DatePatternTest.kt
> +    fun `should match this date time format`() {
can we rename this test name to `should match date format`

2023-06-05 06:38 UTC, androa commented
Thank you for the feedback! I've addressed them now and also tried to remove the unnecessary reformatting of `Grammar.kt` 👍

2023-06-05 17:06 UTC, harikrishnan83 approved these changes
@androa Thanks. Looks good to me.

2023-06-05 17:07 UTC, merged