Support for Multipart Array of parts
specmatic/specmatic pull request #695
Opened 2023-08-07 13:15 UTC by aeoncl

**What**: Adding MultipartFormData part arrays

**Why**: Because in one of our test cases, we needed this feature 

**How**: 
We added a new MultipartFormDataPattern just for arrays of parts.
This new MultipartArrayPattern uses the logic of existing MultipartPatterns to generate Files & Content
We added support in multiple places to ensure Specmatic stub & test can generate test cases.

To set the examples in the OpenApi definition, we use an array of externalValue

**Checklist**:

- [ ] Documentation added to the README.md OR link to PR on https://github.com/specmatic/specmatic-documentation
- [X] Tests
- [ ] Sonar Quality Gate

**Issue ID**:
Closes: #690 

Please let us know how you like our implementation, if everything's okay, we can add documentation for this

2023-08-28 08:14 UTC, aeoncl commented
Hey guys, I'm back from holiday leave ! Feel free to let me know if you have any remarks about this PR 😁

2023-09-04 11:06 UTC, harikrishnan83 commented
@aeoncl welcome back. Hope you had a good holiday. Apologies for the delay in review. We will prioritise this PR shortly.

2023-09-08 10:50 UTC, harikrishnan83 commented on core/src/test/kotlin/in/specmatic/core/MultiPartArrayPatternTest.kt
> +    fun `it should generate multiple patterns when a single example is set`() {
Did you mean to name this as "it should generate only one pattern when there is a single example"?

2023-09-14 08:27 UTC, aeoncl commented on core/src/test/kotlin/in/specmatic/core/MultiPartArrayPatternTest.kt
> +    fun `it should generate multiple patterns when a single example is set`() {
Yes you're right, i'm gonna fix this 😂

2023-09-17 16:19 UTC, joelrosario requested changes

2023-09-17 16:19 UTC, joelrosario commented on core/src/test/kotlin/in/specmatic/core/HttpRequestPatternTest.kt
> +    fun `request with a multipart array should result in a request with multiple files from the row`() {
It's not clear by reading the test how the file names translate to the content of the respective files being sent out by the contract test. Can you update your assertions to clarify this.

2023-09-17 16:19 UTC, joelrosario commented on core/src/test/kotlin/in/specmatic/conversions/OpenApiSpecificationTest.kt
> +        @Test
Can you add OpenAPI examples in this sample specification, so that the test can depict how examples would look, based on which contract tests would send out multiple files with the same part name, and update the assertions appropriately.

For reference, you can look at helloMultipartWithExamples.yaml and the tests that use this file.

2023-09-20 08:46 UTC, aeoncl commented on core/src/test/kotlin/in/specmatic/conversions/OpenApiSpecificationTest.kt
> +        @Test
Okay, i'll look into it !

2023-09-21 18:14 UTC, joelrosario commented
Thanks @aeoncl, will take a closer look tomorrow.

2023-10-03 11:41 UTC, joelrosario requested changes
Thanks @aeoncl for adding those clarifying assertions.

Can we have a couple of integration tests to round this off please.

**An end-to-end stubbing test**
This would show that a multipart file request would be understood by Specmatic stub.
1. There is already the specification in `OpenApiSpecificationTest.support for multipart form data part array`.
2. The test can stub it out using HttpStub, and set an expectation for receiving 2 files and return the object {"status": "done"}. 
3. Then use HttpClient to send a request with 1 file (should return a randomised response)
4. Use HttpClient to send a request with 2 files (should get above response object)

**An end-to-end test for contract tests**
This would test the wiring between all the units (this PR currently has unit tests).

1. There is already the specification in `OpenApiSpecificationTest.support for multipart form data part array`, with examples.
2. Use this to run contract tests (use `OpenApiSpecification.fromYAML("yaml content").toFeature()` to load the YAML directly, or `OpenApiSpecification.fromFile("file path")` to read from a file).
3. You can now use this object to run tests (without an actual API to hit, see how it's done in `ContractAsTest.runContractAsTest`) and assert that 2 file parts were indeed received.

Thanks again @aeoncl, really appreciate the work you've done on this.

2024-02-09 04:29 UTC, joelrosario commented
Hi @aeoncl, we are closing this PR for now, as there has been no activity on it for a while, and the codebase of Specmatic has moved forward quite a lot. If you still intend to complete the implementation of this feature, we'd be happy to accept changes addressing my comments above, either in this PR, or in a new one.

Thankyou for your support and your contributions to this project!

2024-02-09 04:29 UTC, closed without merging

2024-02-18 12:01 UTC, aeoncl commented
Hey Joel ! Sorry for the late reply, we had a lot of changes going on and i don't have the bandwith to keep working on this right now, Thank you and have a nice day :D