Fix AnyPattern nullable bug
specmatic/specmatic pull request #743
Opened 2023-09-22 09:50 UTC by aeoncl

**What**: Changing how newBaseOn & listOf of the AnyPattern handle the presence of NullPattern in their PatternList

**Why**: The use of the method single() on the PatternList throwed an Exception when trying to generate a nullable array

**How**: Adding checks and excluding the NullablePattern from the selection in specific cases

**Checklist**:

- [NA] Documentation added to the README.md OR link to PR on https://github.com/specmatic/specmatic-documentation
- [NA] Tests
- [NA] Sonar Quality Gate

**Issue ID**:
Closes: #742

2023-09-22 10:48 UTC, joelrosario commented
Hi @aeoncl, thanks for the PR, we were amazed to see it just few minutes after we replied to your issue!

Would be great if you could add a test for the new code.

2023-09-22 10:49 UTC, joelrosario requested changes
Need a test for the new functionality.

2023-09-22 11:43 UTC, aeoncl commented
On it ! i tried to get away without writing one lol

2023-09-26 10:59 UTC, joelrosario commented
@aeoncl thanks, we've added a failing test for a case where AnyPattern is an enum, and made it pass. We've also refactored your tests a bit.

This PR is good to merge.

Github will add you to our contributors list (which we'd like very much) if the email in your commits is the same as the email in your Github profile. Can you confirm if this is the case?

2023-09-26 13:23 UTC, aeoncl commented
Thanks ! I don't believe it is :( my git profile keeps getting reset on my work computer for some reason

2023-09-27 09:38 UTC, harikrishnan83 commented
@aeoncl can you please make one commit (can be just a single line change or a new line) on this PR with your email id that is associated with the Github Profile?

2023-09-27 09:46 UTC, aeoncl commented
Last commit has the right user

2023-09-27 11:55 UTC, joelrosario approved these changes
Looks good to me, thanks @aeoncl!

2023-09-27 11:55 UTC, merged