updated the code to handle the lower case authorization header for issue 658, added test case for the same as well
specmatic/specmatic pull request #938
Opened 2024-01-25 17:57 UTC by vishal07111998

I have updated[ BearerSecurityScheme.kt ](https://github.com/znsio/specmatic/blob/main/core/src/main/kotlin/in/specmatic/conversions/BearerSecurityScheme.kt), the method **matches** to handle lower case authorization header for **fetch apis** as per the [issue](https://github.com/znsio/specmatic/issues/658).
Earlier the code was designed such a way where it was only handling the scenarios where "**Authorization**" header is in capitalize where as Fetch APIs make the headers in lower case by default.

"I need to implement changes to prevent the 'cannot find the authorization header' error in Specmatic when testing Fetch APIs. The objective is to enable Specmatic to gracefully test Fetch APIs without encountering this specific issue."

I have added one more condition in elvis operator to check for "**authorization**" as well with "**Authorization**"

The change was in the [file](https://github.com/znsio/specmatic/blob/main/core/src/main/kotlin/in/specmatic/conversions/BearerSecurityScheme.kt)

**earlier the code was**
```
   val authHeaderValue: String = it[AUTHORIZATION]
                ?: return Result.Failure("$AUTHORIZATION header is missing in request")
```
   **After the changes** 
   
 ```
 val authHeaderValue: String = it["Authorization"] ?: it["authorization"]
            ?: return Result.Failure("$AUTHORIZATION header is missing in request")
```

            
  New test case is added in this [file](https://github.com/znsio/specmatic/blob/main/core/src/test/kotlin/in/specmatic/conversions/BearerSecuritySchemeTest.kt) 

  ```
  @Test
    fun `Bearer security scheme matches requests with lower case authorization header set`() {
        val requestWithBearer = HttpRequest(method = "POST", path = "/customer", headers = mapOf("authorization" to "bearer foo"))
        assertThat(scheme.matches(requestWithBearer).isSuccess()).isTrue
    }
```

**Checklist**:

- [ ] Documentation added to the README.md OR link to PR on https://github.com/specmatic/specmatic-documentation- N/A
- [x] Tests
- [ ] Sonar Quality Gate- N/A

**Issue ID**:
[Closes: #658](https://github.com/znsio/specmatic/issues/658)

2024-02-03 18:31 UTC, harikrishnan83 commented
@vishal07111998 Thanks for your PR. Looks like you have only taken care of the stub side. Can you also please check if we are able to send lower cased "authorization" header as part of request when running contract tests?

The [suggestion](https://github.com/znsio/specmatic/issues/658#issuecomment-1569975291) from @androa maybe helpful on this.

2024-02-04 11:58 UTC, harikrishnan83 requested changes
@vishal07111998 Thanks again for the PR. Can you please take at the comments I have added?

2024-02-04 12:20 UTC, vishal07111998 commented
> @vishal07111998 Thanks again for the PR. Can you please take at the comments I have added?

Yes @harikrishnan83 , Already started working on it

2024-02-10 17:19 UTC, harikrishnan83 approved these changes
Looks good. A few more changes may need to be done after the merge. Thanks a lot @vishal07111998

2024-02-10 17:19 UTC, merged